project:
  type: website
  output-dir: docs

website:
  title: "belkhuu.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Projects
      - href: assignments.qmd
        text: Assignments
      - href: blogposts.qmd
        text: Blog Posts
      - href: Uyen_Van_Khuu_Resume.pdf
        text: Resume

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual